version: "3.8"
name: code-test
services:
  db:
    container_name: database
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  nestjs-app:
    container_name: backend
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend-api:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydatabase"
    depends_on:
      - db

volumes:
  postgres_data:
